### ISSUE TITLE
YUI EOL was Aug 2014

### ISSUE THREAD

**Issue by bootstraponline** [Ricardonacif/touch_action#2]
Active development on YUI was halted in [Aug 2014](http://yahooeng.tumblr.com/post/96098168666/important-announcement-regarding-yui). Is there any alternative JavaScript framework that's actively developed which could power touch actions?

**Comment by bootstraponline** [comment]
I found [jquery simulate](https://github.com/jquery/jquery-simulate) however it's not any different in terms of EOL status. Hopefully the selenium [mobile spec](https://github.com/SeleniumHQ/mobile-spec) with touch actions gets adopted soon.

**Comment by Ricardonacif** [comment]
Good to know. What exactly is this Selenium Mobile Spec?

**Comment by bootstraponline** [comment]
> What exactly is this Selenium Mobile Spec?

It's an upcoming version of Selenium that defines new features such as [gestures](https://github.com/SeleniumHQ/mobile-spec/blob/d092f19128182199f4fafdb78534958102547283/spec-draft.md#touch-gestures). I've been looking for a simple way to do drag & drop automation for angular.js and it doesn't seem possible.

**Comment by Ricardonacif** [comment]
Nice to know. It's time for Selenium to get more mobile friendly. Did this gem helped you with that?

**Comment by bootstraponline** [comment]
It didn't. I think the issue is specific to the app I'm testing since manually writing JS to trigger [WheelEvents](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent) wasn't effective. In angular, it's easier to just add a method to the app that knows how to scroll. I'm closing this issue since it's not a bug in the gem.
