### ISSUE TITLE
NameError: uninitialized constant RSpec

### ISSUE THREAD

**Issue by bootstraponline** [Ricardonacif/touch_action#3]
I was testing out the gem in Pry and found this error on require.

```
> require 'touch_action'
NameError: uninitialized constant RSpec
from /.rvm/gems/ruby-2.1.5/gems/touch_action-1.3.0/lib/touch_action/capybara_rspec_helper.rb:17:in `<top (required)>'
```

**Comment by Ricardonacif** [comment]
RSpec is a development dependency. Try running: bundle install --with-development-dependencies

**Comment by bootstraponline** [comment]
> RSpec is a development dependency.

No, it's a runtime dependency which is the reason [for this bug](https://github.com/Ricardonacif/touch_action/blob/master/lib/touch_action/capybara_rspec_helper.rb#L17). If someone doesn't have rspec installed then they will get an error upon requiring the gem. The rspec helper is required in touch_action. To fix, use `defined?(RSpec)`

**Comment by Ricardonacif** [comment]
Hmm got it. Will update it when I got time. Feel free to do a pull request as well if you can.

**Comment by bootstraponline** [comment]
I think this'll work: https://github.com/Ricardonacif/touch_action/pull/4

**Comment by Ricardonacif** [comment]
Thanks!
