### ISSUE TITLE
NoMethodError: undefined method `touch_action'

### ISSUE THREAD

**Issue by dspeiser** [Ricardonacif/touch_action#6]
I am currently trying to use touch_action for some capybara tests, but I keep getting an undefined method error.
The gem is installed, and is required within my script:

``` ruby
require 'touch_action'
require 'touch_action/capybara_rspec_helper'
```

``` ruby
gem 'touch_action'
```

``` ruby
[3] pry(#<Object>)> page.driver
=> #<Capybara::Selenium::Driver:0x00000108e1f678
 @app=nil,
 @browser=#<Selenium::WebDriver::Driver:0x4f12631b69e1a21e browser=:chrome>,
 @exit_status=nil,
 @frame_handles={},
 @options={:browser=>:chrome}>
[4] pry(#<Object>)> page.driver.touch_action
NoMethodError: undefined method `touch_action' for #<Capybara::Selenium::Driver:0x00000108e1f678>
from (pry):4:in `block in <top (required)>'
[5] pry(#<Object>)> page.driver.browser
=> #<Selenium::WebDriver::Driver:0x4f12631b69e1a21e browser=:chrome>
[6] pry(#<Object>)> page.driver.browser.touch_action
NoMethodError: undefined method `touch_action' for #<Selenium::WebDriver::Driver:0x4f12631b69e1a21e browser=:chrome>
from (pry):6:in `block in <top (required)>'
[7] pry(#<Object>)> respond_to?('touch_action')
=> false
```

Please take a look into this, or let me know what I am doing wrong. Thank you.

**Comment by Ricardonacif** [comment]
Hey @D-Speiser, when using capybara the `touch_action` method is available within the rspec `it` block. If you're not using Rspec, try calling `page.touch_action(:swipe)` for example and let me know if it works.

**Comment by dspeiser** [comment]
Does not work. Same undefined method.

**Comment by Ricardonacif** [comment]
Do you have the selenium-webdriver gem explicitly required on the Gemfile? Try `require 'touch_action/selenium-webdriver'`

**Comment by dspeiser** [comment]
Added it. Still getting the same error.

``` ruby
[2] pry(#<Object>)> page.touch_action(:swipe)
NoMethodError: undefined method `touch_action' for #<Capybara::Session>
from (pry):2:in `block in <top (required)>'
```

**Comment by Ricardonacif** [comment]
Oh, just realized on your first example, you gotta call the `touch_action` method on an Element object, not on the browser, like:

`page.driver.browser.find_element(class: 'myclass').touch_action(:swipe)` for instance.

**Comment by dspeiser** [comment]
That worked. Thank you!

**Comment by Ricardonacif** [comment]
Awesome :+1:

**Comment by Vygo** [comment]
Hey, Ricardo
I am working with Daniel and was wondering if it is possible somehow to make this work with just
touch_action("#elementid", :swipe). Everything else from capybara functionality doesn't make you to use
page.driver.browser

**Comment by Ricardonacif** [comment]
So far that's possible if you're using Rspec. What testing framework are you using? Is just a matter of making the helper available there.

**Comment by Vygo** [comment]
We are using Cucumber/Capybara stack with SitePrism for page objects

**Comment by Ricardonacif** [comment]
I've never used SitePrism before. If the elements there inherits from Selenium-webdriver elements, than `@home.search_button.touch_action(:swipe)` should work. If not, would be just a matter of adding the touch_action method to SitePrism's element class. I won't have time to work on that during the next days, but feel free to do a pull request. You can figure it out just by seeing how touch_action gem is doing with watir-webdriver elements.

**Comment by Vygo** [comment]
Sounds good, we'll try
