### ISSUE TITLE
Poltergeist support?

### ISSUE THREAD

**Issue by IDragonfire** [Ricardonacif/touch_action#7]
This gem does not support Poltergeist as driver, or?
https://github.com/teampoltergeist/poltergeist

I get this error message

```
undefined method `touch_action' for #<Capybara::Element tag="body"> (NoMethodError)
```

step

```
elemnt = page.find('body')
element.touch_action(:move, xdist: -70, ydist: 0,  duration: 500)
```

spec_helper

```
require 'touch_action'
```

Gemfile

```
gem 'touch_action', '~> 1.3.2'
```

**Comment by Ricardonacif** [comment]
So far it supports Capybara only if you use it with RSpec. But that's something easy to change, I'll take a look on that.

**Comment by IDragonfire** [comment]
Thank you very much, specially for your fast response.

**Comment by Ricardonacif** [comment]
Hey @IDragonfire, I've added support to capybara native elements. It should work now. Please update the gem and let me know here so I can close the issue.

Thanks,

**Comment by IDragonfire** [comment]
`touch_action` method is now defined for `Capybara::Element`, but this error occure:

```
undefined method `execute_script' for #<Capybara::Poltergeist::Browser:0x0000000663c350> (NoMethodError)
```

Mabye `page.execute_script` instead of `driver.browser.execute_script` solves the problem?
https://github.com/Ricardonacif/touch_action/blob/master/lib/touch_action/capybara_element.rb#L9
https://github.com/jnicklas/capybara#scripting

Thank you very much for your effort ;)

**Comment by Ricardonacif** [comment]
@IDragonfire opps I didn't know that Poltergeist implemented his own browser. page.execute_script won't work there. I'll take a look at that later.

**Comment by IDragonfire** [comment]
@Ricardonacif Thank you very much ;)

Ps.: I only found this:
https://github.com/teampoltergeist/poltergeist/blob/f146de3f452737f16079782a12d31dcbf49dcd2b/lib/capybara/poltergeist/driver.rb#L139

https://github.com/teampoltergeist/poltergeist/search?utf8=%E2%9C%93&q=execute+script

> Poltergeist is a driver for Capybara. It allows you to run your Capybara tests on a headless WebKit     browser, provided by PhantomJS.

https://github.com/teampoltergeist/poltergeist#poltergeist---a-phantomjs-driver-for-capybara

**Comment by Ricardonacif** [comment]
Cool. I'll have time to implement it during the week ok?

**Comment by IDragonfire** [comment]
@Ricardonacif I will test it as soon as you publish it ;)

**Comment by IDragonfire** [comment]
@Ricardonacif any progress?

**Comment by Ricardonacif** [comment]
@IDragonfire sorry man I didn't have time yet. Will see if I can do it later tonight.

**Comment by IDragonfire** [comment]
@Ricardonacif Thanks ;)

**Comment by adamlangsner** [comment]
@IDragonfire I'm running into the same issue with poltergeist. Did you find a workaround?

**Comment by IDragonfire** [comment]
@adamlangsner sorryy .. I found no solution ...
